apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: kvns
spec:
  replicas: 4
  selector:
    matchLabels:
      env: prod
      app: nginx
  template:
    metadata:
      labels:
        env: prod
        app: nginx
    spec:
      containers:
        - name: mynginx
          image: DOCKER_IMAGE
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerpasswd



